### ISSUE TITLE
undefined reference to `errs'

### ISSUE THREAD

**Issue by dakhnod** [csBlueChip/FlipperZero_plugin_PWM#1]
I am trying to compile this plugin for the unleashed firmware, and I am getting the error `undefined reference to 'errs'`.
I can not find the use of errs anywhere else in the plugins.

How can I make this work with unleashed?
Or what other firmware works?

**Comment by csBlueChip** [comment]
Sorry about that ...it was cross linking with another "bc" plugin on my machine ...please try again now and let me know if it is fixed on unleashed.

**Comment by dakhnod** [comment]
@csBlueChip yep, works now, thank you.

Would be great if there way a way to test servos with this.
A servo requires a 50Hz PWM signal with a duty cycle from 1000us to 2000us, many servos beyond that.

Do you think that that is easily doable?

**Comment by csBlueChip** [comment]
I'm gonna close this issue (as per OP)
Happy to discuss (and implement) [basic] servo control ...could you start a new issue for that please? :) ...You can also find me on the FZ Discord
